networks:
  app_network:
    driver: bridge

services:
  db:
    image: postgres:16
    restart: always
    networks:
      - app_network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    container_name: mediumclone
    volumes:
      - pg-volume:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_network
    container_name: nest-app
    restart: always
    depends_on:
      - db
    environment:
      - PORT=${APP_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
      echo 'Waiting for database...' &&
      sleep 5 &&
      echo 'Running seed...' &&
      npm run db:seed &&
      echo 'Starting application...' &&
      yarn start:dev
      "

volumes:
  pg-volume:
